Use GestionRS

--TABLAS INDEPENDIENTES 
CREATE TABLE ESTABLECIMIENTO(
	ID INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(120) NOT NULL UNIQUE
);
CREATE TABLE PROCESO_GENERADOR(
	ID INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(180) NOT NULL  UNIQUE
);
CREATE TABLE PRESENTACION(
	ID INTEGER  NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(120) NOT NULL UNIQUE
);
CREATE TABLE GESTOR(
	ID INTEGER NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE MECANISMO_ENTREGA(
	ID INTEGER NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE ESTADO_MATERIA(
	ID INTEGER NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE CERTIFICADO(
	ID INT NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(80) NOT NULL UNIQUE
);


--TABLAS RELACIONALES
CREATE TABLE TIPO_RESIDUO(
	ID INTEGER NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(180) NOT NULL UNIQUE 
);
CREATE TABLE GRADO_PELIGROSIDAD(
	ID INTEGER NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL UNIQUE,
);

CREATE TABLE TIPO_RESIDUO_X_GRADO(
	ID INTEGER NOT NULL PRIMARY KEY,
	TIPO_RESIDUO_ID INT,
    GRADO_ID INT,
	CONSTRAINT FK_TipoResiduo_Id_Tipo_Residuo FOREIGN KEY (TIPO_RESIDUO_ID) REFERENCES TIPO_RESIDUO(ID),
    CONSTRAINT FK_Grado_Id_Grado_GradoPligrosidad FOREIGN KEY (GRADO_ID) REFERENCES GRADO_PELIGROSIDAD(ID)
);	

CREATE TABLE GESTION(
	ID INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(120) NOT NULL UNIQUE,
);

CREATE TABLE TIPO_GESTION(
	ID INTEGER NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(120) NOT NULL UNIQUE  
);

CREATE TABLE GESTION_x_TIPO(
	ID INTEGER NOT NULL PRIMARY KEY,
	GESTION_ID INTEGER NOT NULL,
	TIPO_ID INTEGER  NOT NULL,
	CONSTRAINT FK_Gestion_Id_x_Gestion FOREIGN KEY(GESTION_ID)REFERENCES GESTION(ID),
	CONSTRAINT FK_Tipo_Id_x_Tipo_Gestion FOREIGN KEY(TIPO_ID)REFERENCES TIPO_GESTION(ID)
);
CREATE TABLE RESIDUO(
	ID INTEGER NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(255) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(255) NOT NULL,
	TIPO_RESIDUO VARCHAR(255) NOT NULL,
	GRADO_PELIGROSIDAD VARCHAR(100) NOT NULL,
	ESTADO_MATERIA VARCHAR(120) NOT NULL,
);

CREATE TABLE REGISTRO(
	ID INT NOT NULL PRIMARY KEY,
	RESIDUO VARCHAR(120) NOT NULL,
	FECHA DATE NOT NULL,
	DESCRIPCION VARCHAR(250)NOT NULL,
	TIPO_RESIDUO VARCHAR(250) NOT NULL,
	ESTABLECIMIENTO VARCHAR(160) NOT NULL,
	PROCESO_GENERADOR VARCHAR(180)NOT NULL,
	GRADO_PELIGROSIDAD VARCHAR(180)NOT NULL,
	ESTADO VARCHAR(160) NOT NULL,
	CANTIDAD INT NOT NULL,
	GESTION VARCHAR(120) NOT NULL,
	TIPO_GESTION VARCHAR(255) NOT NULL,
	MECANISMO_ENTREGA VARCHAR(180) NOT NULL,
	PRESENTACION VARCHAR(120) NOT NULL,
	GESTOR VARCHAR(120) NOT NULL,
	CERTIFICADO VARCHAR(80)NOT NULL
);